export * from "./loader/Loader"
export * from "./header/Header"
export * from "./footer/Footer"
export * from "./home/Home"
export * from "./blogNews/BlogNews"
export * from "./allNewsImg/AllNewsImg"
export * from "./actuallyImg/ActuallyImg"